name: CD

on:
  workflow_run:
    workflows: [CI]
    types: [completed]

jobs:
  emit:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: codeberg-tiny-lazy

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Zig
        uses: https://github.com/mlugg/setup-zig@v1
        with:
          version: 0.14.0
          use-cache: false

      - name: Run doc step
        run: zig build doc

      - name: Upload artifact for Codeberg Pages
        uses: forgejo/upload-artifact@v4
        with:
          path: zig-out/docs/

  deploy:
    needs: emit

    runs-on: codeberg-tiny-lazy

    steps:
      - name: Check out repository
        uses: actions/checkout@v4
        with:
          ref: pages

      - name: Download artifact for Codeberg Pages
        uses: forgejo/download-artifact@v4

      - name: Deploy documentation to Codeberg Pages
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add -A
          git commit -m "Deploy documentation"
          git push
