name: CI

on:
  push:
    branches: [main]

  pull_request:
    branches: [main]

  workflow_dispatch:

jobs:
  exe:
    runs-on: codeberg-tiny-lazy

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Zig
        uses: https://github.com/mlugg/setup-zig@v1
        with:
          version: master

      - name: Run `exe` step
        run: |
          zig build exe -- -p forgejo && rm -rf liza/
          zig build exe -- -c lib && rm -rf liza/
          zig build exe -- -c prt

  # fmt:
  #   runs-on: codeberg-tiny-lazy

  #   steps:
  #     - name: Check out repository
  #       uses: actions/checkout@v4

  #     - name: Set up Zig
  #       run: |
  #         chmod +x .forgejo/workflows/set_up_zig.sh
  #         ./.forgejo/workflows/set_up_zig.sh

  #     - name: Run `fmt` step
  #       run: zig build fmt
