name: CI

on:
  push:
    branches: [main]

  pull_request:
    branches: [main]

  workflow_dispatch:

jobs:
  exe:
    runs-on: codeberg-tiny

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Zig
        run: |
          chmod +x .forgejo/workflows/set_up_zig.sh
          ./.forgejo/workflows/set_up_zig.sh

          echo "Run `exe` step"
          zig build exe && rm -rf liza/
          zig build exe -- -c lib && rm -rf liza/
          zig build exe -- -c prt

          echo "Run `fmt` step"
          zig build fmt
