name: CI

on:
  push:
    branches: [main]

  pull_request:
    branches: [main]

  workflow_dispatch:

jobs:
  exe:
    runs-on: codeberg-tiny-lazy

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Zig
        uses: https://github.com/mlugg/setup-zig@v1
        with:
            version: master

      - name: Run exe step
        run: |
          zig build exe -- -r forgejo && cd liza/ && zig build && cd ../ && rm -rf liza/
          zig build exe -- -c lib && cd liza/ && zig build && cd ../ && rm -rf liza/
          zig build exe -- -c bld && rm -rf liza/
          zig build exe -- -c app && rm -rf liza/

  fmt:
    runs-on: codeberg-tiny-lazy

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Zig
        uses: https://github.com/mlugg/setup-zig@v1
        with:
            version: master

      - name: Run fmt step
        run: zig build fmt
