name: CI

on:
  push:
    branches: [main]

  pull_request:
    branches: [main]

  workflow_dispatch:

jobs:
  exe:
    runs-on: codeberg-tiny-lazy

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Zig
        run: |
          curl $(curl https://ziglang.org/download/index.json | jq -r '.master."x86_64-linux".tarball') -o zig.tar.xz
          tar -xf zig.tar.xz
          mv zig*/ zig/

      - name: Run `exe` step
        run: |
          ./zig/zig build exe && rm -rf liza/
          ./zig/zig build exe -- -c lib && rm -rf liza/
          ./zig/zig build exe -- -c prt

      - name: Run `fmt` step
        run: ./zig/zig build fmt
