name: CD

on:
  workflow_dispatch:

jobs:
  emit:
    runs-on: codeberg-tiny-lazy

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Zig
        run: |
          chmod +x .forgejo/workflows/set_up_zig.sh
          ./.forgejo/workflows/set_up_zig.sh

      - name: Run `doc` step
        run: zig build doc

      - name: Upload artifact for Codeberg Pages
        uses: forgejo/upload-artifact@v4
        with:
          path: zig-out/doc/

  deploy:
    needs: emit

    runs-on: codeberg-tiny-lazy

    steps:
      - name: Check out repository
        uses: actions/checkout@v4
        with:
          ref: pages

      - name: Download artifact for Codeberg Pages
        uses: forgejo/download-artifact@v4

      - name: Deploy documentation to Codeberg Pages
        run:
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m "Deploy documentation"
          git push
