name: CI

on:
  push:
    branches: [main]

  pull_request:
    branches: [main]

  workflow_dispatch:

jobs:
  ?:
    runs-on: codeberg-tiny-lazy

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Zig
        uses: https://github.com/mlugg/setup-zig@v1

      - name: Run `?` step
        run: zig build ?

  test:
    runs-on: codeberg-tiny-lazy

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Zig
        uses: https://github.com/mlugg/setup-zig@v1

      - name: Run `test` step
        run: zig build test --summary all

  fmt:
    runs-on: codeberg-tiny-lazy

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Zig
        uses: https://github.com/mlugg/setup-zig@v1

      - name: Run `fmt` step
        run: zig build fmt
