name: CI

on:
  push:
    branches: [main]

  pull_request:
    branches: [main]

jobs:
  install:
    runs-on: codeberg-tiny-lazy

    steps:
      - name: Check out repository
        uses: actions/checkout@v5

      - name: Set up Zig
        uses: https://github.com/mlugg/setup-zig@v2
        with:
          use-cache: false

      - name: Run `install` step
        run: zig build install
