when:
  event: [push, pull_request]
  branch: main

steps:
  $s:
    image: kassany/alpine-ziglang:$z
    depends_on: []
    commands: |
      zig build $s

  test:
    image: kassany/alpine-ziglang:$z
    commands: |
      zig build test --summary all

  fmt:
    image: kassany/alpine-ziglang:$z
    commands: |
      zig build fmt
