when:
  event: [push, pull_request]
  branch: main

steps:
  $s:
    image: tensorush/ziglang:latest

    depends_on: [] # enable parallel steps

    commands: |
      zig build $s

  test:
    image: tensorush/ziglang:latest

    commands: |
      zig build test --summary all

  fmt:
    image: tensorush/ziglang:latest

    commands: |
      zig build fmt
