when:
  event: tag
  branch: main
  ref: "refs/tags/v[0-9]+.[0-9]+.[0-9]+"

steps:
  release:
    image: kassany/alpine-ziglang:$z

    environment:
      MINISIGN_SECRET_KEY:
        from_secret: MINISIGN_SECRET_KEY
      MINISIGN_PUBLIC_KEY:
        from_secret: MINISIGN_PUBLIC_KEY

    commands: |
      echo "Set up minisign"
      curl -L https://github.com/jedisct1/minisign/releases/download/0.12/minisign-0.12-linux.tar.gz -o minisign.tar.gz
      tar -xf minisign.tar.gz
      export "PATH=${CI_WORKSPACE}/minisign-linux/x86_64/:${PATH}"

      echo "Run release step"
      zig build release

      echo "Sign release binaries"
      echo "${MINISIGN_SECRET_KEY}" > minisign.key
      minisign -S -s minisign.key -m zig-out/release/*
      echo "${MINISIGN_PUBLIC_KEY}" > zig-out/release/minisign.pub
      rm minisign.key

  publish:
    image: woodpeckerci/plugin-release
    settings:
      files: |
        zig-out/release/*
      api_key:
        from_secret: ACCESS_TOKEN
