when:
  event: [manual]
  branch:
    exclude: pages

depends_on: [ci]

steps:
  emit:
    image: kassany/alpine-ziglang:0.14.0
    commands: |
      zig build doc

  deploy:
    image: alpine/git:edge
    environment:
      TOKEN:
        from_secret: cbtoken
      EMAIL:
        from_secret: cbmail
    commands: |
      git config --global user.email ${EMAIL}
      git config --global user.name "Woodpecker CI"
      git clone --branch pages https://${TOKEN}@codeberg.org/${CI_REPO}.git ${CI_REPO_NAME}
      cd ${CI_REPO_NAME}
      cp -ar ../zig-out/docs/. ./
      git add -A
      git commit -m "Deploy documentation"
      git push
