depends_on: [ci]

when:
  event: [push]
  branch: main

steps:
  emit:
    image: tensorush/ziglang:latest

    commands: zig build doc

  deploy:
    image: alpine/git:latest

    environment:
      TOKEN:
        from_secret: TOKEN
      EMAIL:
        from_secret: EMAIL

    commands: |
      git config --global user.name "Woodpecker CI"
      git config --global user.email $EMAIL
      git clone -b pages https://$TOKEN@codeberg.org/$CI_REPO.git $CI_REPO_NAME
      cd $CI_REPO_NAME
      cp -r ../zig-out/docs/. ./
      git add -A
      git commit -m "Deploy documentation" --allow-empty
      git push
