depends_on: [ci]

when:
  event: [push]
  branch: main

steps:
  emit:
    image: alpine:edge

    commands: |
      echo "Set up Zig"
      apk --no-cache add curl jq
      curl $(curl https://ziglang.org/download/index.json | jq -r '."0.14.0"."x86_64-linux".tarball') -o zig.tar.xz
      tar -xf zig.tar.xz
      mv zig*/ zig/
      export "PATH=$CI_WORKSPACE/zig:$PATH"

      echo "Run doc step"
      zig build doc

  deploy:
    image: alpine/git:edge

    environment:
      TOKEN:
        from_secret: TOKEN
      EMAIL:
        from_secret: EMAIL

    commands: |
      git config --global user.name "Woodpecker CI"
      git config --global user.email $EMAIL
      git clone -b pages https://$TOKEN@codeberg.org/$CI_REPO.git $CI_REPO_NAME
      cd $CI_REPO_NAME
      cp -r ../zig-out/docs/. ./
      git add -A
      git commit -m "Deploy documentation" --allow-empty
      git push
