steps:
  exe:
    image: kassany/alpine-ziglang:0.14.0
    when:
      event: [push, pull_request]
      branch: main
    commands: |
      zig build exe -- -r woodpecker --add-doc --add-cov executable "Executable description." user-handle "User Name" && rm -rf executable/
      zig build exe -- -c lib -r woodpecker --add-doc --add-cov library "Library description." user-handle "User Name" && rm -rf library/
      zig build exe -- -c bld -r woodpecker build "Build description." user-handle "User Name" && rm -rf build/
      zig build exe -- -c app -r woodpecker application "Application description." user-handle "User Name" && rm -rf application/

  fmt:
    image: kassany/alpine-ziglang:0.14.0
    when:
      event: [push, pull_request]
      branch: main
    commands: |
      zig build fmt
