steps:
  ci:
    image: alpine:edge
    when:
      event: [push, pull_request, manual]
      branch: main
    commands: |
      echo "Set up Zig"
      apk --no-cache add git curl jq && curl $(curl https://ziglang.org/download/index.json | jq -r '.master."x86_64-linux".tarball') -o zig.tar.xz && tar -xf zig.tar.xz && mv zig*/ zig/ && export "PATH=$(pwd)/zig:$PATH"
      echo "Run exe step"
      zig build exe -- -r woodpecker --add-doc --add-cov executable "Executable description." user-handle "User Name" && rm -rf executable/
      zig build exe -- -c lib -r woodpecker --add-doc --add-cov library "Library description." user-handle "User Name" && rm -rf library/
      zig build exe -- -c bld -r woodpecker build "Build description." user-handle "User Name" && rm -rf build/
      zig build exe -- -c app -r woodpecker application "Application description." user-handle "User Name" && rm -rf application/
      echo "Run fmt step"
      zig build fmt
