when:
  event: [push, pull_request]
  branch: main

steps:
  run:
    image: tensorush/ziglang:latest
    pull: true

    depends_on: [] # Enable parallel steps

    commands: |
      apk --no-cache add git
      zig build install
      zig build run -- -d -g -k -f executable "Executable description." user-handle "User Name" && rm -rf executable/
      zig build run -- -c lib -d -g -k -f library "Library description." user-handle "User Name" && rm -rf library/
      zig build run -- -c bld build https://upstream.repo.link user-handle "User Name" && rm -rf build/
