when:
  event: [push, pull_request]
  branch: main

steps:
  run:
    image: tensorush/ziglang:latest

    depends_on: [] # enable parallel steps

    commands: |
      zig build run -- -r woodpecker --add-doc --add-cov --add-check executable "Executable description." user-handle "User Name" && rm -rf executable/
      zig build run -- -c lib -r woodpecker --add-doc --add-cov --add-check library "Library description." user-handle "User Name" && rm -rf library/
      zig build run -- -c bld -r woodpecker build "Build description." user-handle "User Name" && rm -rf build/
      zig build run -- -c app -r woodpecker application "Application description." user-handle "User Name" && rm -rf application/

  fmt:
    image: tensorush/ziglang:latest

    commands: zig build fmt
