when:
  event: [push, pull_request]
  branch: main

steps:
  run:
    image: tensorush/ziglang:latest
    pull: true

    depends_on: [] # Enable parallel steps

    commands: |
      apk --no-cache add git

      zig build run -- -d -c -k executable "Executable description." user-handle "User Name"
      cd executable/
      zig build
      zig build run
      zig build doc
      zig build cov
      zig build release
      cd ../
      rm -rf executable/

      zig build run -- -t lib -d -c -k library "Library description." user-handle "User Name"
      cd library/
      zig build
      zig build run
      zig build doc
      zig build cov
      cd ../
      rm -rf library/

      zig build run -- -t bld build https://upstream.repo.link user-handle "User Name"
      rm -rf build/

  fmt:
    image: tensorush/ziglang:latest
    pull: true

    commands: zig build fmt
