when:
  event: [push, pull_request]
  branch: main

steps:
  run:
    image: tensorush/ziglang:latest

    depends_on: [] # enable parallel steps

    commands: |
      apk --no-cache add git
      zig build run -- -r woodpecker --add-doc --add-cov --add-check exe executable "Executable description." user-handle "User Name" && rm -rf executable/
      zig build run -- -r woodpecker --add-doc --add-cov --add-check lib library "Library description." user-handle "User Name" && rm -rf library/
      zig build run -- -r woodpecker bld build "Build description." user-handle "User Name" && rm -rf build/
      zig build run -- -r woodpecker app application "Application description." user-handle "User Name" && rm -rf application/

  fmt:
    image: tensorush/ziglang:latest

    commands: zig build fmt
