name: CI

on:
  push:
    branches: [main]

  pull_request:
    branches: [main]

jobs:
  install:
    runs-on: ubuntu-22.04

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Zig
        uses: mlugg/setup-zig@v2

      - name: Run `install` step
        run: zig build install$c
