name: CI

on:
  push:
    branches: [main]

  pull_request:
    branches: [main]

  workflow_dispatch:

concurrency:
  group: ci
  cancel-in-progress: true

jobs:
  install:
    runs-on: ubuntu-22.04

    steps:
      - name: Check out repository
        uses: actions/checkout@v5

      - name: Set up Zig
        uses: mlugg/setup-zig@v2

      - name: Run `install` step
        run: zig build install$c
