name: CD

on:
  workflow_run:
    workflows: [CI]
    types: [completed]

jobs:
  release:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}

    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Zig
        uses: mlugg/setup-zig@v1
        with:
          version: 0.14.0

      - name: Set up minisign
        env:
          REF: ${{ github.ref }}
          EVENT_REF: ${{ github.event.workflow_run.referenced_workflows[0].ref }}
        run: |
          echo $REF
          echo $EVENT_REF
          wget https://github.com/jedisct1/minisign/releases/download/0.12/minisign-0.12-linux.tar.gz
          tar -xf minisign-0.12-linux.tar.gz --directory ${HOME}
          echo "${HOME}/minisign-linux/x86_64/" >> $GITHUB_PATH

      - name: Run release step
        run: zig build release

      - name: Sign release binaries
        env:
          MINISIGN_SECRET_KEY: ${{ secrets.MINISIGN_SECRET_KEY }}
          MINISIGN_PUBLIC_KEY: ${{ secrets.MINISIGN_PUBLIC_KEY }}
        run: |
          echo "${MINISIGN_SECRET_KEY}" > minisign.key
          minisign -S -s minisign.key -m zig-out/release/*
          echo "${MINISIGN_PUBLIC_KEY}" > zig-out/release/minisign.pub
          rm minisign.key

      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          body: |
            Archived binary files can be verified as follows:
            minisign -Vm <file> -P minisign.pub
          files: zig-out/release/*
          generate_release_notes: true
