name: CI

on:
  push:
    branches: [main]

  pull_request:
    branches: [main]

  workflow_dispatch:

jobs:
  exe:
    runs-on: ubuntu-22.04

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Zig
        uses: mlugg/setup-zig@v1
        with:
          version: master

      - name: Set up kcov
        run: sudo apt install kcov

      - name: Run exe step
        run: |
          rm -rf liza/
          zig build exe -- --add-doc --add-cov liza "Zig codebase initializer." tensorush "Jora Troosh" && cd liza/ && zig fetch --save git+https://github.com/Hejsil/zig-clap && zig build && zig build exe -- "All your codebase are belong to us." && cd ../ && rm -rf liza/
          zig build exe -- -c lib --add-doc --add-cov liza "Zig codebase initializer." tensorush "Jora Troosh" && cd liza/ && zig build && cd ../ && rm -rf liza/
          zig build exe -- -c bld liza "Zig codebase initializer." tensorush "Jora Troosh" && rm -rf liza/
          zig build exe -- -c app liza "Zig codebase initializer." tensorush "Jora Troosh" && rm -rf liza/

  fmt:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Zig
        uses: mlugg/setup-zig@v1
        with:
          version: master

      - name: Run fmt step
        run: zig build fmt
