name: CI

on:
  push:
    branches: [main]

  pull_request:
    branches: [main]

  workflow_dispatch:

jobs:
  exe:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Zig
        uses: mlugg/setup-zig@v1

      - name: Set up kcov
        run: sudo apt install kcov

      - name: Run `exe` step
        run: |
          zig build exe && cd liza/ && zig build && cd ../ && rm -rf liza/
          zig build exe -- -c lib && cd liza/ && zig build && cd ../ && rm -rf liza/
          zig build exe -- -c prt

  fmt:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Zig
        uses: mlugg/setup-zig@v1

      - name: Run `fmt` step
        run: zig build fmt
