name: CI

on:
  push:
    branches: [main]

  pull_request:
    branches: [main]

jobs:
  run:
    runs-on: ubuntu-22.04

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Zig
        uses: mlugg/setup-zig@v1

      - name: Set up kcov
        run: sudo apt install kcov

      - name: Run `run` step
        run: |
          zig build run -- --add-doc --add-cov --add-check executable "Executable description." user-handle "User Name" && cd executable/ && zig fetch --save git+https://codeberg.org/tensorush/argzon.git && zig build && zig build run && zig build check && zig build release && cd ../ && rm -rf executable/
          zig build run -- -c lib --add-doc --add-cov --add-check library "Library description." user-handle "User Name" && cd library/ && zig build && zig build run && zig build check && cd ../ && rm -rf library/
          zig build run -- -c bld build "Build description." user-handle "User Name" && rm -rf build/
          zig build run -- -c app application "Application description." user-handle "User Name" && rm -rf application/

  fmt:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Zig
        uses: mlugg/setup-zig@v1

      - name: Run `fmt` step
        run: zig build fmt
