name: CI

on:
  push:
    branches: [main]

  pull_request:
    branches: [main]

  workflow_dispatch:

concurrency:
  group: ci
  cancel-in-progress: true

jobs:
  run:
    runs-on: ubuntu-22.04

    steps:
      - name: Check out repository
        uses: actions/checkout@v5

      - name: Set up Zig
        uses: mlugg/setup-zig@v2

      - name: Set up kcov
        run: sudo apt install kcov

      - name: Run `install` step
        run: zig build install

      - name: Run `run` step
        run: |
          zig build run -- -r github --add-doc --add-cov --add-check executable "Executable description." user-handle "User Name" && cd executable/ && zig build && zig build run && zig build check && zig build release && cd ../ && rm -rf executable/
          zig build run -- -c lib -r github --add-doc --add-cov --add-check library "Library description." user-handle "User Name" && cd library/ && zig build && zig build run && zig build check && cd ../ && rm -rf library/
          zig build run -- -c bld -r github build "Build description." user-handle "User Name" && rm -rf build/
